config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :member_applications do
    member do
      get :acknowledge
    end
  end
  resources :members
  resources :partner_companies

end

app/models/partner_company.rb
class PartnerCompany < ActiveRecord::Base
  
end

app/controllers/partner_companies_controller.rb
class PartnerCompaniesController < ApplicationController
  before_action :set_partner_company, only: [:show, :edit, :update, :destroy]

  # GET /partner_companies
  # GET /partner_companies.json
  def index
    @partner_companies = PartnerCompany.all
  end

  # GET /partner_companies/1
  # GET /partner_companies/1.json
  def show
  end

  # GET /partner_companies/new
  def new
    @partner_company = PartnerCompany.new
  end

  # GET /partner_companies/1/edit
  def edit
  end

  # POST /partner_companies
  # POST /partner_companies.json
  def create
    @partner_company = PartnerCompany.new(partner_company_params)

    respond_to do |format|
      if @partner_company.save
        format.html { redirect_to @partner_company, notice: 'Partner company was successfully created.' }
        format.json { render :show, status: :created, location: @partner_company }
      else
        format.html { render :new }
        format.json { render json: @partner_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partner_companies/1
  # PATCH/PUT /partner_companies/1.json
  def update
    respond_to do |format|
      if @partner_company.update(partner_company_params)
        format.html { redirect_to @partner_company, notice: 'Partner company was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner_company }
      else
        format.html { render :edit }
        format.json { render json: @partner_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partner_companies/1
  # DELETE /partner_companies/1.json
  def destroy
    @partner_company.destroy
    respond_to do |format|
      format.html { redirect_to partner_companies_url, notice: 'Partner company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner_company
      @partner_company = PartnerCompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_company_params
      params.require(:partner_company).permit(:name)
    end
end

app/helpers/partner_companies_helper.rb
module PartnerCompaniesHelper
end

app/views/partner_companies/_form.html.erb
<%= form_for(@partner_company) do |f| %>
  <% if @partner_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner_company.errors.count, "error") %> prohibited this partner_company from being saved:</h2>

      <ul>
      <% @partner_company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partner_companies/edit.html.erb
<h1>Editing Partner Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @partner_company %> |
<%= link_to 'Back', partner_companies_path %>

app/views/partner_companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Partner Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partner_companies.each do |partner_company| %>
      <tr>
        <td><%= partner_company.name %></td>
        <td><%= link_to 'Show', partner_company %></td>
        <td><%= link_to 'Edit', edit_partner_company_path(partner_company) %></td>
        <td><%= link_to 'Destroy', partner_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner company', new_partner_company_path %>

app/views/partner_companies/new.html.erb
<h1>New Partner Company</h1>

<%= render 'form' %>

<%= link_to 'Back', partner_companies_path %>

app/views/partner_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @partner_company.name %>
</p>

<%= link_to 'Edit', edit_partner_company_path(@partner_company) %> |
<%= link_to 'Back', partner_companies_path %>