config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :member_applications do
    member do
      get :acknowledge
    end
  end
  resources :members
  resources :partner_companies

end

app/models/member_application.rb
class MemberApplication < ActiveRecord::Base
  has_one :member
  belongs_to :partner_company
  belongs_to :leader, class_name: 'Member'
  belongs_to :administrator, class_name: 'Member'
  belongs_to :applicant, class_name: 'Member'
  belongs_to :acknowledger, class_name: 'Member'

  enum request_type: {shinki: 0, koshin: 1, sakujo: 2}
  enum status: {shitagaki: 0, shoninmachi: 1, sagyochu: 2, hishonin: 3, kanryo: 4}

  def name_kanji
    return last_name_kanji + ' ' + first_name_kanji
  end

  def name_kana
    return last_name_kana + ' ' + first_name_kana
  end

  def name_romaji
    return last_name_romaji + ' ' + first_name_romaji
  end


  # FIXME: before_saveのONオプションが効かない
  before_save :set_applicant_info#, :if => params[:action
  before_save :set_acknowledge_info#, :on => :acknowledge

  private

  def set_applicant_info
    # TODO: 申請者をログインユーザにする
    self.applicant = Member.shain.first
    self.application_date = DateTime.now
  end

  def set_acknowledge_info
    # TODO: 承認者をログインユーザにする
    self.acknowledger = Member.shain.last
    self.acknowledge_date = DateTime.now
  end

end

app/controllers/member_applications_controller.rb
class MemberApplicationsController < ApplicationController
  before_action :set_member_application, only: [:show, :edit, :update, :destroy, :acknowledge]
  # アクション実行時に権限認証を行う
  load_and_authorize_resource

  # GET /member_applications
  # GET /member_applications.json
  def index
    @member_applications = MemberApplication.all
    authorize! :read, MemberApplication
  end

  # GET /member_applications/1
  # GET /member_applications/1.json
  def show
  end

  # GET /member_applications/new
  def new
    @member_application = MemberApplication.new
    @partner_companies = PartnerCompany.all.order(name: :asc)
    @members = Member.existing
  end

  # GET /member_applications/1/edit
  def edit
    @partner_companies = PartnerCompany.all.order(name: :asc)
    @members = Member.existing
  end

  def acknowledge
    @partner_companies = PartnerCompany.all.order(name: :asc)
    @members = Member.existing
  end

  # POST /member_applications
  # POST /member_applications.json
  def create
    @member_application = MemberApplication.new(member_application_params)

    respond_to do |format|
      if @member_application.save
        format.html { redirect_to @member_application, notice: 'Member application was successfully created.' }
        format.json { render :show, status: :created, location: @member_application }
      else
        format.html { render :new }
        format.json { render json: @member_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_applications/1
  # PATCH/PUT /member_applications/1.json
  def update
    respond_to do |format|
      if @member_application.update(member_application_params)
        format.html { redirect_to @member_application, notice: 'Member application was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_application }
      else
        format.html { render :edit }
        format.json { render json: @member_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_applications/1
  # DELETE /member_applications/1.json
  def destroy
    @member_application.destroy
    respond_to do |format|
      format.html { redirect_to member_applications_url, notice: 'Member application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_application
      @member_application = MemberApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_application_params
      params.require(:member_application).permit(:request_type, :status, :member_id, :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :last_name_romaji, :first_name_romaji, :project_name, :partner_company_id, :reconsignment_company_name, :leader_id, :administrator_id, :work_location, :passport_no, :email_address, :email_flg, :internet_flg, :global_id, :esd_email_address, :to_acknowedger, :to_applicant, :application_date, :applicant_id, :acknowledge_date, :acknowledge_id, :partner_flg)
    end
end

app/helpers/member_applications_helper.rb
module MemberApplicationsHelper
end

app/views/member_applications/_detail.html.erb
<table>
  <tbody>
    <tr>
      <th><%= MemberApplication.human_attribute_name :request_type %></th>
      <td><%= @member_application.request_type_i18n %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :status %></th>
      <td><%= @member_application.status_i18n %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :last_name_kanji %><%= MemberApplication.human_attribute_name :first_name_kanji %></th>
      <td><%= @member_application.name_kanji %></td>
    </tr>
    <tr>
      <th>(カナ)</th>
      <td><%= @member_application.name_kana %></td>
    </tr>
    <tr>
      <th>(ローマ字)</th>
      <td><%= @member_application.name_romaji %></td>
    </tr>
    <tr>
      <td colspan=2><hr></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :partner_flg %></th>
      <td><%= @member_application.partner_flg %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :partner_company %></th>
      <td><%= @member_application.partner_company.try(:name) %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :project_name %></th>
      <td><%= @member_application.project_name %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :reconsignment_company_name %></th>
      <td><%= @member_application.reconsignment_company_name %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :leader %></th>
      <td><%= @member_application.leader.try(:name_kanji) %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :administrator %></th>
      <td><%= @member_application.administrator.try(:name_kanji) %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :work_location %></th>
      <td><%= @member_application.work_location %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :email_flg %></th>
      <td><%= @member_application.email_flg %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :internet_flg %></th>
      <td><%= @member_application.internet_flg %></td>
    </tr>
    <tr>
      <td colspan=2><hr></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :passport_no %></td>
      <td><%= @member_application.passport_no %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :email_address %></th>
      <td><%= @member_application.email_address %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :global_id %></th>
      <td><%= @member_application.global_id %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :esd_email_address %></th>
      <td><%= @member_application.esd_email_address %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :to_acknowedger %></th>
      <td><%= @member_application.to_acknowedger %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :to_applicant %></th>
      <td><%= @member_application.to_applicant %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :applicant %></th>
      <td><%= @member_application.applicant.try(:name_kanji) %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :application_date %></th>
      <td><%= @member_application.application_date %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :acknowledger %></th>
      <td><%= @member_application.acknowledger.try(:name_kanji) %></td>
    </tr>
    <tr>
      <th><%= MemberApplication.human_attribute_name :acknowledge_date %></th>
      <td><%= @member_application.acknowledge_date %></td>
    </tr>
  </tbody>
</table>

app/views/member_applications/_form.html.erb
<%= form_for(@member_application) do |f| %>
  <% if @member_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_application.errors.count, "error") %> prohibited this member_application from being saved:</h2>

      <ul>
      <% @member_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </tr>
  <% end %>

  <%= f.hidden_field :request_type %>
  <%= f.hidden_field :status %>
  <%= f.hidden_field :member_id %>
  <%= f.hidden_field :application_date %>
  <%= f.hidden_field :applicant %>

  <table>
    <tbody>
      <tr>
        <th><%= f.label :last_name_kanji %><%= f.label :first_name_kanji %></th>
        <td><%= f.text_field :last_name_kanji, size: 8 %> <%= f.text_field :first_name_kanji, size: 8 %></td>
      </tr>
      <tr>
        <th>(カナ)</th>
        <td><%= f.text_field :last_name_kana, size: 8 %> <%= f.text_field :first_name_kana, size: 8 %></td>
      </tr>
      <tr>
        <th>(ローマ字)</th>
        <td><%= f.text_field :last_name_romaji, size: 8 %> <%= f.text_field :first_name_romaji, size: 8 %></td>
      </tr>
      <tr>
        <td colspan=2><hr></td>
      </tr>
      <tr>
        <td colspan=2 align=center>
          <label>NRI<%= f.radio_button :partner_flg, 'false' %></label>
          <label>パートナー<%= f.radio_button :partner_flg, 'true' %></label>
        </td>
      </tr>
      <tr>
        <th><%= f.label :partner_company %></th>
        <td><%= f.collection_select :partner_company_id, @partner_companies, :id, :name, { include_blank: '- - 選択 - -' } %></td>
      </tr>
      <tr>
        <th><%= f.label :project_name %></th>
        <td><%= f.text_field :project_name %></td>
      </tr>
      <tr>
        <th><%= f.label :reconsignment_company_name %></th>
        <td><%= f.text_field :reconsignment_company_name %></td>
      </tr>
      <tr>
        <th><%= f.label :leader %></th>
        <td><%= f.collection_select :leader_id, @members.partner, :id, :name_kanji, { include_blank: '- - 選択 - -' } %></td>
      </tr>
      <tr>
        <th><%= f.label :administrator %></th>
        <td><%= f.collection_select :administrator_id, @members.shain, :id, :name_kanji, { include_blank: '- - 選択 - -' } %></td>
      </tr>
      <tr>
        <th><%= f.label :work_location %></th>
        <td><%= f.text_field :work_location %></td>
      </tr>
      <tr>
        <th><%= f.label :email_flg %></th>
        <td><%= f.check_box :email_flg %></td>
      </tr>
      <tr>
        <th><%= f.label :internet_flg %></th>
        <td><%= f.check_box :internet_flg %></td>
      </tr>
      <tr>
        <td colspan=2><hr></td>
      </tr>
      <tr>
        <th><%= f.label :passport_no %></td>
        <td><%= f.text_field :passport_no %></td>
      </tr>
      <tr>
        <th><%= f.label :email_address %></th>
        <td><%= f.text_field :email_address %></td>
      </tr>
      <tr>
        <th><%= f.label :global_id %></th>
        <td><%= f.text_field :global_id %></td>
      </tr>
      <tr>
        <th><%= f.label :esd_email_address %></th>
        <td><%= f.text_field :esd_email_address %></td>
      </tr>
      <tr>
        <th><%= f.label :to_acknowedger %></th>
        <td><%= f.text_area :to_acknowedger, :size => "30x3" %></td>
      </tr>
      <!--
      <tr>
        <th><%= f.label :to_applicant %></th>
        <td><%= f.text_area :to_applicant, :size => "30x3" %></td>
      </tr>
      -->
    </tbody>
  </table>
  <div>
    <label><%= f.check_box :status, { class: 'draft' }, 'shitagaki', 'shoninmachi' %>下書き保存</label>
  </div>
  <div class="actions">
    <%= f.submit '更新' %>
  </div>
<% end %>

app/views/member_applications/_form_acknowledge.html.erb
<%= form_for(@member_application) do |f| %>
  <% if @member_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_application.errors.count, "error") %> prohibited this member_application from being saved:</h2>

      <ul>
      <% @member_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </tr>
  <% end %>

  <%= f.hidden_field :status, value: :sagyochu %>
  <table>
    <tbody>
      <tr>
        <th><%= f.label :to_applicant %></th>
        <td><%= f.text_area :to_applicant, :size => "30x3" %></td>
      </tr>
    </tbody>
  </table>
  <div class="actions">
    <%= f.submit '承認' %>
  </div>
<% end %>

app/views/member_applications/acknowledge.html.erb
<h1>承認画面</h1>

<%= render 'detail' %>
<%= render 'form_acknowledge' %>

<%= link_to '詳細', @member_application %> |
<%= link_to '戻る', member_applications_path %>

app/views/member_applications/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '詳細', @member_application %> |
<%= link_to '戻る', member_applications_path %>

app/views/member_applications/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>異動対応申請一覧</h1>

<div>
  <%= link_to '新規申請', new_member_application_path %>
</div>

<br>

<table width=100% border=1>
  <thead>
    <tr>
      <th><%= MemberApplication.human_attribute_name :id %></th>
      <th><%= MemberApplication.human_attribute_name :request_type %></th>
      <th><%= MemberApplication.human_attribute_name :status %></th>
      <th>氏名</th>
      <th>所属</th>
      <th><%= MemberApplication.human_attribute_name :passport_no %></th>
      <th><%= MemberApplication.human_attribute_name :email_address %></th>
      <th><%= MemberApplication.human_attribute_name :email_flg %></th>
      <th><%= MemberApplication.human_attribute_name :internet_flg %></th>
      <th><%= MemberApplication.human_attribute_name :global_id %></th>
      <th><%= MemberApplication.human_attribute_name :applicant %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @member_applications.each do |member_application| %>
      <tr>
        <td><%= member_application.id %></td>
        <td><%= member_application.request_type_i18n %></td>
        <td><%= member_application.status_i18n %></td>
        <td>
          <%= member_application.last_name_kanji %> <%= member_application.first_name_kanji %>
        </td>
        <td><%= member_application.partner_flg ? member_application.partner_company.try(:name) : '社員' %></td>
        <td><%= member_application.passport_no %></td>
        <td><%= member_application.email_address %></td>
        <td>
          <%= member_application.email_flg == true ? '●' : '' %>
        </td>
        <td>
          <%= member_application.internet_flg == true ? '●' : '' %>
        </td>
        <td><%= member_application.global_id %></td>
        <td><%= member_application.applicant.try(:last_name_kanji) %> <%= member_application.applicant.try(:first_name_kanji) %></td>
        <td><%= link_to '詳細', member_application %></td>
        <td><%= link_to '修正', edit_member_application_path(member_application) %></td>
        <% # TODO: 承認待ち　かつ　承認者のみ表示されるようにする %>
        <td><%= link_to_if member_application.status=='shoninmachi', '承認', acknowledge_member_application_path(member_application) do |name| '' end %></td>
        <!--<td><%= link_to 'destroy', member_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/member_applications/new.html.erb
<h1>新規申請</h1>

<%= render 'form' %>

<%= link_to 'Back', member_applications_path %>

app/views/member_applications/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= render 'detail' %>

<%= link_to 'Edit', edit_member_application_path(@member_application) %> |
<%= link_to 'Back', member_applications_path %>