config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'

  resources :member_applications do
    member do
      get :acknowledge
    end
  end
  resources :members
  resources :partner_companies

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :partner_company

  scope :existing, -> { where(deleted_flg: 'false') }
  scope :shain, -> { where(partner_flg: 'false') }
  scope :partner, -> { where(partner_flg: 'true') }
  scope :partner_belongs_to, ->(partner_company) { where(partner_flg: 'true', partner_company: partner_company).order(name: :asc) }

  def name_kanji
    return last_name_kanji + ' ' + first_name_kanji
  end

  def name_kana
    return last_name_kana + ' ' + first_name_kana
  end

  def name_romaji
    return last_name_romaji + ' ' + first_name_romaji
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  # アクション実行時に権限認証を行う
  load_and_authorize_resource

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
    @partner_companies = PartnerCompany.all.order(name: :asc)
  end

  # GET /members/1/edit
  def edit
    @partner_companies = PartnerCompany.all.order(name: :asc)
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:password, :last_name_kanji, :first_name_kanji, :last_name_kana, :first_name_kana, :last_name_romaji, :first_name_romaji, :deleted_flg, :partner_flg, :passport_no, :email_address, :global_id, :production_terminal_room_pass, :esd_email_address, :esd_internet_flg, :internet_flg, :email_flg, :partner_company_id, :leader_id, :project_name, :administrator_id, :work_location, :reconsignment_company_name)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :last_name_kanji %><br>
    <%= f.text_field :last_name_kanji %>
  </div>
  <div class="field">
    <%= f.label :first_name_kanji %><br>
    <%= f.text_field :first_name_kanji %>
  </div>
  <div class="field">
    <%= f.label :last_name_kana %><br>
    <%= f.text_field :last_name_kana %>
  </div>
  <div class="field">
    <%= f.label :first_name_kana %><br>
    <%= f.text_field :first_name_kana %>
  </div>
  <div class="field">
    <%= f.label :last_name_romaji %><br>
    <%= f.text_field :last_name_romaji %>
  </div>
  <div class="field">
    <%= f.label :first_name_romaji %><br>
    <%= f.text_field :first_name_romaji %>
  </div>
  <div class="field">
    <%= f.label :deleted_flg %><br>
    <%= f.check_box :deleted_flg %>
  </div>
  <div class="field">
    <%= f.label :partner_flg %><br>
    <%= f.check_box :partner_flg %>
  </div>
  <div class="field">
    <%= f.label :passport_no %><br>
    <%= f.text_field :passport_no %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :global_id %><br>
    <%= f.text_field :global_id %>
  </div>
  <div class="field">
    <%= f.label :production_terminal_room_pass %><br>
    <%= f.check_box :production_terminal_room_pass %>
  </div>
  <div class="field">
    <%= f.label :esd_email_address %><br>
    <%= f.text_field :esd_email_address %>
  </div>
  <div class="field">
    <%= f.label :esd_internet_flg %><br>
    <%= f.check_box :esd_internet_flg %>
  </div>
  <div class="field">
    <%= f.label :internet_flg %><br>
    <%= f.check_box :internet_flg %>
  </div>
  <div class="field">
    <%= f.label :email_flg %><br>
    <%= f.check_box :email_flg %>
  </div>
  <div class="field">
    <%= f.label :partner_company %><br>
    <%= f.collection_select :partner_company_id, @partner_companies, :id, :name, { include_blank: '- - 選択 - -' } %>
  </div>
  <div class="field">
    <%= f.label :leader_id %><br>
    <%= f.number_field :leader_id %>
  </div>
  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :administrator_id %><br>
    <%= f.number_field :administrator_id %>
  </div>
  <div class="field">
    <%= f.label :work_location %><br>
    <%= f.text_field :work_location %>
  </div>
  <div class="field">
    <%= f.label :reconsignment_company_name %><br>
    <%= f.text_field :reconsignment_company_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>マスタリスト</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Last name kanji</th>
      <th>First name kanji</th>
      <th>Last name kana</th>
      <th>First name kana</th>
      <th>Last name romaji</th>
      <th>First name romaji</th>
      <th>Deleted flg</th>
      <th>Partner flg</th>
      <th>Passport no</th>
      <th>Email address</th>
      <th>Global</th>
      <th>Production terminal room pass</th>
      <th>Esd email address</th>
      <th>Esd internet flg</th>
      <th>Internet flg</th>
      <th>Email flg</th>
      <th>Partner company</th>
      <th>Leader</th>
      <th>Project name</th>
      <th>Administrator</th>
      <th>Work location</th>
      <th>Reconsignment company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.password %></td>
        <td><%= member.last_name_kanji %></td>
        <td><%= member.first_name_kanji %></td>
        <td><%= member.last_name_kana %></td>
        <td><%= member.first_name_kana %></td>
        <td><%= member.last_name_romaji %></td>
        <td><%= member.first_name_romaji %></td>
        <td><%= member.deleted_flg %></td>
        <td><%= member.partner_flg %></td>
        <td><%= member.passport_no %></td>
        <td><%= member.email_address %></td>
        <td><%= member.global_id %></td>
        <td><%= member.production_terminal_room_pass %></td>
        <td><%= member.esd_email_address %></td>
        <td><%= member.esd_internet_flg %></td>
        <td><%= member.internet_flg %></td>
        <td><%= member.email_flg %></td>
        <td><%= member.partner_company %></td>
        <td><%= member.leader_id %></td>
        <td><%= member.project_name %></td>
        <td><%= member.administrator_id %></td>
        <td><%= member.work_location %></td>
        <td><%= member.reconsignment_company_name %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @member.password %>
</p>

<p>
  <strong>Last name kanji:</strong>
  <%= @member.last_name_kanji %>
</p>

<p>
  <strong>First name kanji:</strong>
  <%= @member.first_name_kanji %>
</p>

<p>
  <strong>Last name kana:</strong>
  <%= @member.last_name_kana %>
</p>

<p>
  <strong>First name kana:</strong>
  <%= @member.first_name_kana %>
</p>

<p>
  <strong>Last name romaji:</strong>
  <%= @member.last_name_romaji %>
</p>

<p>
  <strong>First name romaji:</strong>
  <%= @member.first_name_romaji %>
</p>

<p>
  <strong>Deleted flg:</strong>
  <%= @member.deleted_flg %>
</p>

<p>
  <strong>Partner flg:</strong>
  <%= @member.partner_flg %>
</p>

<p>
  <strong>Passport no:</strong>
  <%= @member.passport_no %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @member.email_address %>
</p>

<p>
  <strong>Global:</strong>
  <%= @member.global_id %>
</p>

<p>
  <strong>Production terminal room pass:</strong>
  <%= @member.production_terminal_room_pass %>
</p>

<p>
  <strong>Esd email address:</strong>
  <%= @member.esd_email_address %>
</p>

<p>
  <strong>Esd internet flg:</strong>
  <%= @member.esd_internet_flg %>
</p>

<p>
  <strong>Internet flg:</strong>
  <%= @member.internet_flg %>
</p>

<p>
  <strong>Email flg:</strong>
  <%= @member.email_flg %>
</p>

<p>
  <strong>Partner company:</strong>
  <%= @member.partner_company %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @member.leader_id %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @member.project_name %>
</p>

<p>
  <strong>Administrator:</strong>
  <%= @member.administrator_id %>
</p>

<p>
  <strong>Work location:</strong>
  <%= @member.work_location %>
</p>

<p>
  <strong>Reconsignment company name:</strong>
  <%= @member.reconsignment_company_name %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>